### ISSUE TITLE
An API to detect crash inside worker thread

### ISSUE THREAD

**Issue by Bubbler-4** [w3reality/wasm-mt#3]
I found that the current `Thread` API does not support the situation where the worker crashes while running the given task. (Please correct me if I'm wrong) So I made a [patched version](https://github.com/Bubbler-4/seed-app-counter/tree/master/wasm-mt-patch) inside [a small demo app](https://github.com/Bubbler-4/seed-app-counter/tree/master/wasm-mt-patch) (live version [here](https://wasm-worker-example.netlify.app/)). The patch adds an `onerror` hook to the created JS `Worker` instance, and an `is_terminated()` method to allow polling if the thread crashed or not.

Should I open a PR on this?

**Comment by j-devel** [comment]
Thank you for the feedback!

> I found that the current Thread API does not support the situation where the worker crashes while running the given task.

That's true; and thanks for point this out!  It's been a while since 'src/atw.rs' was implemented, and handling the worker's crash cases has been totally forgotten!   So I'd be very happy to have such a PR that improves the situation.

Regarding the patch, I have some suggestions though.

According to the demo, it's really nice that we can trigger [the closure made by `create_onerror()`](https://github.com/Bubbler-4/seed-app-counter/blob/4209dd634df4e4198a093e1b9b71994878ee5273/wasm-mt-patch/src/atw.rs#L165) _upon Rust panics_.  But within that closure, can it be like broadcasting Promise rejections (maybe sth like [this](https://github.com/Bubbler-4/seed-app-counter/blob/4209dd634df4e4198a093e1b9b71994878ee5273/wasm-mt-patch/src/atw.rs#L224)), rather than signalling "termination" of the worker?  I think this will allow us to [actually handle the error](https://github.com/Bubbler-4/seed-app-counter/blob/4209dd634df4e4198a093e1b9b71994878ee5273/src/runner.rs#L123-L124) more naturally.

As far as I tested, the worker is still "alive" even after `computation_panic()` crashes.  So I guess we shouldn't treat it as the same as worker termination?

**Comment by Bubbler-4** [comment]
> But within that closure, can it be like broadcasting Promise rejections (maybe sth like this), rather than signalling "termination" of the worker?

Yeah, that sounds much better than my initial idea. Even better if the thread can be actually *reused* after a job crashes, though I guess we'll need an experiment for that part.

**Comment by Bubbler-4** [comment]
I tried copying the body of `cancel_pending_requests` function into `create_onerror()`. It works pretty well (the `Err` result is correctly passed as the result of `exec!`), and the thread can indeed accept more jobs without terminating. [The updated demo is here.](https://wasm-worker-example.netlify.app/)

One major(?) caveat is that every crash inside the thread seems to occupy the memory it was holding. If you repeatedly click the "error" button like 30 or 40 times and then click the "good" button, you get OOM panic on *that* too. A good news is that it can still be fixed by terminating the thread and starting a new one.

I'm honestly not sure how to deal with multiple jobs being run at once. I guess it is probably safe to reject all jobs (as it is now) since other parts of Rust code could be affected by the panic inside the thread.

**Comment by j-devel** [comment]
Nice to hear that it worked as we expected! (with an interesting caveat 😄 )

> One major(?) caveat is that every crash inside the thread seems to occupy the memory it was holding. 

Looks related to [this issue](https://github.com/rust-lang/rust/issues/58874). So, once  https://github.com/WebAssembly/exception-handling becomes available in future, I think we will be able to do something about it (e.g. informing the developer about the ID of the exact panic'ed job, and/or providing a callback interface).

> how to deal with multiple jobs being run at once. I guess it is probably safe to reject all jobs (as it is now) since other parts of Rust code could be affected by the panic inside the thread.

Yeah, and due to the point above, it's likely that the developer ends up calling `Thread::terminate()` for now(?)

Now, it looks like we are ready; will you file a PR?

**Comment by Bubbler-4** [comment]
I guess you can `cargo publish` the new version now :)

**Comment by j-devel** [comment]
Indeed.  `wasm-mt = "0.1.2"` published!
